### ISSUE TITLE
 No connected devices

### ISSUE THREAD

**Issue by SheptunovaAA** [e13mort/STF-gradle-plugin#3]
Hi! 
I try to use your plugin with this instructions (https://habrahabr.ru/company/yandex/blog/338038/), but when I try to use I have a problem:

```
* What went wrong:
Execution failed for task ':keystore-repository:connectedDebugAndroidTest'.
> com.android.builder.testing.api.DeviceException: No connected devices!

```
My top-level gradle file:

 ```
   dependencies {
...
        classpath "com.github.e13mort:stf-gradle-plugin:0.2.3"
    }
}
...
project.tasks.whenTaskAdded {
    Task task ->
        println task.getName()
        if(task.getName() == 'cAT') {
            println("YES")
            tasks.dependsOn(connectedToSmartphoneTestFarm)
        }
}

apply plugin: 'stf-gradle-plugin'
apply plugin: 'android-reporting'

farmSettings {
    baseUrl = '...url...'
    apiKey = '..key..'
    adbPath = '$ANDROID_HOME/sdk/platform-tools'
    timeout = 60
}
```

I use it like this:
./gradlew cAT 
./gradlew :app:connectedDebugAndroidTest -PSTF_COUNT=2

In logs I can see, that running tasks:
```
 connectToSmartphoneTestFarm
disconnectFromSmartphoneTestFarm
mergeAndroidReports
```
But have result at the end - no Connected Device. What problem it can be?

**Comment by SheptunovaAA** [comment]
First of all, notice, that you've add your 'access token' and 'adb key' to your STF farm before start.

Ok, i've made this all work, but only with this fixes:
1. farmSettings.baseUrl = 'basuStfURL/api/v1/' (take your look at '/api/v1/')
2. to reduce error 'no connected device' you ALWAYS MUST call 
`./gradlew connectToSmartphoneTestFarm` 
before you call main task to run your Android tests like this:
`./gradlew :module:connectedDebugAndroidTest`
And make sure, that you call full-named task 'connectedDebugAndroidTest', not it shortcut version 'cAT' 

@e13mort , please, fix instructions about this bugs or try to help me, where I am wrong

**Comment by e13mort** [comment]
Hi Alena. 
1. Yes, thats definitely should be mentioned in the instructions.
2. That's strange because the connection task should be attached automatically during the test run process. Could you run your test task with the --info flag enabled and show me the log, please?

**Comment by SheptunovaAA** [comment]
Of course, here you are (but it is very non-informative):

```
> Task :keystore-repository:connectedDebugAndroidTest FAILED
Putting task artifact state for task ':keystore-repository:connectedDebugAndroidTest' into context took 0.0 secs.
Up-to-date check for task ':keystore-repository:connectedDebugAndroidTest' took 0.0 secs. It is not up-to-date because:
  Task.upToDateWhen is false.

:keystore-repository:connectedDebugAndroidTest (Thread[Task worker for ':',5,main]) completed. Took 0.004 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':keystore-repository:connectedDebugAndroidTest'.
> com.android.builder.testing.api.DeviceException: No connected devices!
```

Here are logs with --stacktrace 

```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':keystore-repository:connectedDebugAndroidTest'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.internal.UncheckedException: com.android.builder.testing.api.DeviceException: No connected devices!
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:63)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:40)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:76)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:780)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:747)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 29 more
Caused by: com.android.builder.testing.api.DeviceException: No connected devices!
        at com.android.builder.testing.ConnectedDeviceProvider.init(ConnectedDeviceProvider.java:126)
        at com.android.build.gradle.internal.tasks.DeviceProviderInstrumentTestTask.runTests(DeviceProviderInstrumentTestTask.java:140)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        ... 41 more


```

**Comment by e13mort** [comment]
Is there was the '--info' flag at the first log? A task with the flag should produce much more output than the usual run. And there should be some useful lines started with "STF" key.

**Comment by SheptunovaAA** [comment]
Yes, first log with --info, like this:
`./gradlew :keystore-repository:connectedDebugAndroidTest --info`

**Comment by e13mort** [comment]
Is that the total task's output? I don't see the preparation and compilation steps. You could save the output to a file with "./gradlew <task> --info > log.txt"

**Comment by SheptunovaAA** [comment]
Here you are - full log of './gradlew :keystore-repository:connectedDebugAndroidTest --info' command.
But this log does not contain 'stf' word at all. And doesn't have any reasons of problem with connection to devices =(

**Comment by e13mort** [comment]
You're right, there's no 'stf' mentions. Could you please try to reproduce this behavior with the sample project https://github.com/e13mort/stf-gradle-plugin-sample ? Just clone it and run as you do it with your main project.

**Comment by SheptunovaAA** [comment]
Yes, this example working good. 

In my case It seems to problem be in gradle file: I put dependencies to stf-plugin and 'farmSettings' into top-level (project) gradle file. After I try to add all of this settings to specific module and run it - all start working... 

So, if I want to use stf-plugin I should put it settings to all project modules (build.gradle), where I have Android tests

**Comment by e13mort** [comment]
Yes, the plugin configuration is module-specific, not project. So it should be placed inside modules. The problem here is with the plugin description. I'll fix this.

**Comment by SheptunovaAA** [comment]
Thanks for help!

**Comment by SheptunovaAA** [comment]
Thanks for help!
